//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ISourceWs")]
public interface ISourceWs
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISourceWs/GetActions", ReplyAction="http://tempuri.org/ISourceWs/GetActionsResponse")]
    string GetActions();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISourceWs/GetActions", ReplyAction="http://tempuri.org/ISourceWs/GetActionsResponse")]
    System.Threading.Tasks.Task<string> GetActionsAsync();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ISourceWsChannel : ISourceWs, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class SourceWsClient : System.ServiceModel.ClientBase<ISourceWs>, ISourceWs
{
    
    public SourceWsClient()
    {
    }
    
    public SourceWsClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public SourceWsClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public SourceWsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public SourceWsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string GetActions()
    {
        return base.Channel.GetActions();
    }
    
    public System.Threading.Tasks.Task<string> GetActionsAsync()
    {
        return base.Channel.GetActionsAsync();
    }
}
