//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoWS.Models
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Akcija", Namespace="http://schemas.datacontract.org/2004/07/DemoWS.Models")]
    public partial class Akcija : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ActionsField;
        
        private string CurrentDocumentStatusField;
        
        private string DescriptionField;
        
        private string StatusField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Actions
        {
            get
            {
                return this.ActionsField;
            }
            set
            {
                this.ActionsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrentDocumentStatus
        {
            get
            {
                return this.CurrentDocumentStatusField;
            }
            set
            {
                this.CurrentDocumentStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IDestinationWs")]
public interface IDestinationWs
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDestinationWs/SubmitActions", ReplyAction="http://tempuri.org/IDestinationWs/SubmitActionsResponse")]
    string SubmitActions(DemoWS.Models.Akcija[] akcije, string email);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDestinationWs/SubmitActions", ReplyAction="http://tempuri.org/IDestinationWs/SubmitActionsResponse")]
    System.Threading.Tasks.Task<string> SubmitActionsAsync(DemoWS.Models.Akcija[] akcije, string email);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IDestinationWsChannel : IDestinationWs, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class DestinationWsClient : System.ServiceModel.ClientBase<IDestinationWs>, IDestinationWs
{
    
    public DestinationWsClient()
    {
    }
    
    public DestinationWsClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public DestinationWsClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public DestinationWsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public DestinationWsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string SubmitActions(DemoWS.Models.Akcija[] akcije, string email)
    {
        return base.Channel.SubmitActions(akcije, email);
    }
    
    public System.Threading.Tasks.Task<string> SubmitActionsAsync(DemoWS.Models.Akcija[] akcije, string email)
    {
        return base.Channel.SubmitActionsAsync(akcije, email);
    }
}
